### ISSUE TITLE
Small suggestion regarding login routes

### ISSUE THREAD

**Issue by mcummings128** [learn-co-curriculum/sessions_controller_readme#10]
It may be helpful to show readers how the custom routes are setup in routes.rb pertaining to /login instead of just saying they should be made. Since users are brand new with this material and may still be struggling with custom routes, it would probably help them to see what the routes here actually look like.

get “/login”, to: “sessions#new”
post “/login”, to: “sessions#create”

**Comment by drakeltheryuujin** [comment]
We have updated the materials and your feedback has been incorporated. Thanks!
