### ISSUE TITLE
lesson order

### ISSUE THREAD

**Issue by Lukeghenco** [learn-co-curriculum/sessions_controller_readme#2]
I think the lessons are in the wrong order, on learn.co. I believe the session lesson and session lab are supposed to be before the login and login lab

**Comment by jmburges** [comment]
Hey Luke! Thanks for the issue.

So this readme is effectively a refactoring readme. We cover sessions a ton in Sinatra, and then cover them again in the cookies/sesisons reading. Sessions without the concept of login/logout seems a bit difficult and hard to explain. It's just such an easy use case for sessions. So! we put the sessions controller stuff after the login/logout. It refactors all of the sessions stuff from the login/logout stuff into it's own controller where it belongs. Does that make sense?

Maybe we should add a note on this reading that we are effectively refactoring the previous reading?

**Comment by Lukeghenco** [comment]
Ok it just seemed like I was doing the same thing twice just in opposite order

Sincerely,

Luke Ghenco
Full Stack Web Developer
808-3667650
lukeghenco@gmail.com
www.lukeghenco.com
www.github.com/lukeghenco
www.linkedin.com/in/luke-ghenco-9b1a77a0
